# docker-compose.yml
# Command docker-compose --env-file user.env pull --parallel
version: '3.3'
services:
 LDES_SERVER:
    image: ${DOCKER_REPO:-ghcr.io/informatievlaanderen}/ldes-server:${LDES_SERVER_TAG:-20230112t1553}
 LDI_WORKBENCH_NIFI :
    image: ${DOCKER_REPO:-ghcr.io/informatievlaanderen}/ldi-workbench-nifi:${LDI_WORKBENCH_NIFI_TAG:-20230407T130526}
 LDI_ORCHESTRATOR:
    image: ${DOCKER_REPO:-ghcr.io/informatievlaanderen}/ldi-orchestrator:${LDI_ORCHESTRATOR_TAG:-20230407T130529}
# .....

